import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import ProductList from "../components/ProductsList";
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
			<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
			</Head>
			<div> <ProductList/></div>
			{/* <main>Welcome Home!</main> */}
		</>
	)
}
