import Head from 'next/head'
import Intro from '@/sections/Intro'
import Products from '@/sections/Products'

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
			<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
			</Head>
			<main>
				<h1>Welcome Home!</h1>{' '}
			</main>
			<Intro />
			<Products />
		</>
	)
}
